# Generated by Django 6.0.6 on 2026-07-25 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('municipios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='municipio',
            options={'ordering': ['nome'], 'verbose_name': 'Município', 'verbose_name_plural': 'Municípios'},
        ),
        migrations.AlterField(
            model_name='municipio',
            name='altitude',
            field=models.IntegerField(verbose_name='Altitude (m)'),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro'),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='estado',
            field=models.CharField(default='SP', max_length=2, verbose_name='UF'),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='nome',
            field=models.CharField(max_length=100, unique=True, verbose_name='Município'),
        ),
    ]
