# Generated by Django 6.0.6 on 2026-06-23 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('municipios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Geada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperatura_prevista', models.DecimalField(decimal_places=2, max_digits=5)),
                ('risco', models.DecimalField(decimal_places=2, max_digits=5)),
                ('nivel_alerta', models.CharField(choices=[('BAIXO', 'Baixo'), ('MEDIO', 'Médio'), ('ALTO', 'Alto'), ('CRITICO', 'Crítico')], max_length=10)),
                ('data_previsao', models.DateField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='municipios.municipio')),
            ],
        ),
    ]
