# Generated by Django 6.0.6 on 2026-09-25 15:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('municipios', '0002_alter_municipio_options_alter_municipio_altitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntelligenceInterpretation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rule_id', models.CharField(max_length=100, verbose_name='Identificação da regra')),
                ('rule_version', models.CharField(blank=True, max_length=50, null=True, verbose_name='Versão da regra')),
                ('result', models.JSONField(verbose_name='Resultado canônico')),
                ('channel', models.CharField(blank=True, max_length=50, null=True, verbose_name='Canal')),
                ('severity', models.CharField(blank=True, max_length=50, null=True, verbose_name='Severidade')),
                ('score', models.FloatField(blank=True, null=True, verbose_name='Score')),
                ('confidence', models.FloatField(blank=True, null=True, verbose_name='Confiança')),
                ('factors', models.JSONField(blank=True, null=True, verbose_name='Fatores')),
                ('analysis_timestamp', models.DateTimeField(verbose_name='Data/hora da análise')),
                ('provenance', models.JSONField(blank=True, null=True, verbose_name='Proveniência')),
                ('coordinator_version', models.CharField(blank=True, max_length=50, null=True, verbose_name='Versão do coordenador')),
                ('policy_version', models.CharField(blank=True, max_length=50, null=True, verbose_name='Versão da política')),
                ('explainability', models.JSONField(blank=True, null=True, verbose_name='Explicabilidade')),
                ('idempotency_key', models.CharField(max_length=255, unique=True, verbose_name='Chave de idempotência')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='intelligence_interpretations', to='municipios.municipio', verbose_name='Município')),
            ],
            options={
                'verbose_name': 'Interpretação de Inteligência',
                'verbose_name_plural': 'Interpretações de Inteligência',
                'db_table': 'intelligence_interpretation',
                'ordering': ['-analysis_timestamp', '-created_at'],
                'indexes': [models.Index(fields=['municipio', 'analysis_timestamp'], name='intel_interp_mun_date_idx'), models.Index(fields=['rule_id', 'analysis_timestamp'], name='intel_interp_rule_date_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('confidence__gte', 0.0), ('confidence__isnull', True), _connector='OR'), name='intel_confidence_nonnegative')],
            },
        ),
    ]
