# Generated by Django 6.0.6 on 2026-06-23 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('municipios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperatura', models.DecimalField(decimal_places=2, max_digits=5)),
                ('umidade', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pressao', models.DecimalField(decimal_places=2, max_digits=7)),
                ('velocidade_vento', models.DecimalField(decimal_places=2, max_digits=5)),
                ('data_coleta', models.DateTimeField(auto_now_add=True)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='climas', to='municipios.municipio')),
            ],
            options={
                'verbose_name': 'Clima',
                'verbose_name_plural': 'Dados Climáticos',
            },
        ),
    ]
