# Generated by Django 6.0.6 on 2026-06-23 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clima', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clima',
            name='precipitacao',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
