# Generated by Django 6.0.6 on 2026-07-25 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clima', '0002_clima_precipitacao'),
        ('municipios', '0002_alter_municipio_options_alter_municipio_altitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClimateCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('OPEN_METEO', 'Open-Meteo')], default='OPEN_METEO', max_length=20, verbose_name='Provedor')),
                ('payload', models.JSONField(verbose_name='Payload')),
                ('collected_at', models.DateTimeField(verbose_name='Coletado em')),
                ('expires_at', models.DateTimeField(verbose_name='Expira em')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='climate_cache', to='municipios.municipio', verbose_name='Município')),
            ],
            options={
                'verbose_name': 'Cache Climático',
                'verbose_name_plural': 'Caches Climáticos',
                'ordering': ['-collected_at'],
            },
        ),
        migrations.CreateModel(
            name='WeatherStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('OPEN_METEO', 'Open-Meteo')], default='OPEN_METEO', max_length=20, verbose_name='Provedor')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_stations', to='municipios.municipio', verbose_name='Município')),
            ],
            options={
                'verbose_name': 'Estação Climática',
                'verbose_name_plural': 'Estações Climáticas',
                'ordering': ['municipio__nome', 'provider'],
            },
        ),
        migrations.DeleteModel(
            name='Clima',
        ),
        migrations.AddConstraint(
            model_name='climatecache',
            constraint=models.UniqueConstraint(fields=('municipio', 'provider'), name='unique_cache_provider'),
        ),
        migrations.AddConstraint(
            model_name='weatherstation',
            constraint=models.UniqueConstraint(fields=('municipio', 'provider'), name='unique_station_provider'),
        ),
    ]
