# Generated by Django 6.0.6 on 2026-08-11 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clima', '0003_climatecache_weatherstation_delete_clima_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climatecache',
            name='provider',
            field=models.CharField(choices=[('OPEN_METEO', 'Open-Meteo'), ('INMET', 'INMET'), ('CEMADEN', 'CEMADEN'), ('NOAA', 'NOAA')], default='OPEN_METEO', max_length=20, verbose_name='Provedor'),
        ),
        migrations.AlterField(
            model_name='weatherstation',
            name='provider',
            field=models.CharField(choices=[('OPEN_METEO', 'Open-Meteo'), ('INMET', 'INMET'), ('CEMADEN', 'CEMADEN'), ('NOAA', 'NOAA')], default='OPEN_METEO', max_length=20, verbose_name='Provedor'),
        ),
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_date', models.DateField(verbose_name='Data da previsão')),
                ('temperatura_minima', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Temperatura mínima')),
                ('temperatura_maxima', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Temperatura máxima')),
                ('umidade', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Umidade')),
                ('precipitacao', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Precipitação')),
                ('probabilidade_geada', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Probabilidade de geada')),
                ('probabilidade_granizo', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Probabilidade de granizo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='clima.weatherstation', verbose_name='Estação')),
            ],
            options={
                'verbose_name': 'Previsão',
                'verbose_name_plural': 'Previsões',
                'ordering': ['forecast_date'],
                'indexes': [models.Index(fields=['station'], name='clima_forec_station_dc4bdf_idx'), models.Index(fields=['forecast_date'], name='clima_forec_forecas_d23460_idx')],
                'constraints': [models.UniqueConstraint(fields=('station', 'forecast_date'), name='unique_station_forecast')],
            },
        ),
        migrations.CreateModel(
            name='WeatherObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation_time', models.DateTimeField(verbose_name='Data/hora da observação')),
                ('temperatura', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Temperatura')),
                ('umidade', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Umidade')),
                ('pressao', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Pressão')),
                ('velocidade_vento', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Velocidade do vento')),
                ('direcao_vento', models.PositiveSmallIntegerField(verbose_name='Direção do vento')),
                ('precipitacao', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Precipitação')),
                ('cobertura_nuvens', models.PositiveSmallIntegerField(verbose_name='Cobertura de nuvens')),
                ('codigo_tempo', models.PositiveSmallIntegerField(verbose_name='Código do tempo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='clima.weatherstation', verbose_name='Estação')),
            ],
            options={
                'verbose_name': 'Observação Climática',
                'verbose_name_plural': 'Observações Climáticas',
                'ordering': ['-observation_time'],
                'indexes': [models.Index(fields=['station'], name='clima_weath_station_ba9db2_idx'), models.Index(fields=['observation_time'], name='clima_weath_observa_01dfea_idx')],
                'constraints': [models.UniqueConstraint(fields=('station', 'observation_time'), name='unique_station_observation')],
            },
        ),
    ]
