# Generated by Django 6.0.6 on 2026-08-15 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clima', '0004_alter_climatecache_provider_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalWeatherDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('temperatura_media', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Temperatura média')),
                ('temperatura_minima', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Temperatura mínima')),
                ('temperatura_maxima', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Temperatura máxima')),
                ('precipitacao', models.DecimalField(decimal_places=1, default=0, max_digits=8, verbose_name='Precipitação')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_weather', to='clima.weatherstation', verbose_name='Estação')),
            ],
            options={
                'verbose_name': 'Histórico Meteorológico Diário',
                'verbose_name_plural': 'Históricos Meteorológicos Diários',
                'ordering': ['data'],
                'indexes': [models.Index(fields=['station'], name='clima_histo_station_ccf19c_idx'), models.Index(fields=['data'], name='clima_histo_data_d0cb7d_idx'), models.Index(fields=['station', 'data'], name='clima_histo_station_6a220b_idx')],
                'constraints': [models.UniqueConstraint(fields=('station', 'data'), name='unique_station_historical_daily')],
            },
        ),
    ]
