# Generated by Django 6.0.6
#
# AgroClima Café — FASE 1
# Contrato meteorológico canônico
#
# Migração incremental sobre 0005_historicalweatherdaily.
# Nenhum campo legado é removido ou alterado.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "clima",
            "0005_historicalweatherdaily",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="weatherobservation",
            name="precipitacao_1h",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=6,
                null=True,
                verbose_name="Precipitação - 1 hora",
            ),
        ),
        migrations.AddField(
            model_name="weatherobservation",
            name="precipitacao_24h",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=8,
                null=True,
                verbose_name="Precipitação - 24 horas",
            ),
        ),
        migrations.AddField(
            model_name="weatherobservation",
            name="chuva_agora",
            field=models.BooleanField(
                blank=True,
                null=True,
                verbose_name="Chuva ocorrendo agora",
            ),
        ),
        migrations.AddField(
            model_name="weatherobservation",
            name="condicao_tempo",
            field=models.CharField(
                blank=True,
                max_length=30,
                null=True,
                verbose_name="Condição meteorológica",
            ),
        ),
        migrations.AddField(
            model_name="weatherobservation",
            name="tipo_fonte",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                verbose_name="Tipo da fonte",
            ),
        ),
        migrations.AddField(
            model_name="weatherobservation",
            name="coletado_em",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Coletado em",
            ),
        ),
        migrations.AddField(
            model_name="weatherobservation",
            name="qualidade_dado",
            field=models.CharField(
                blank=True,
                max_length=30,
                null=True,
                verbose_name="Qualidade do dado",
            ),
        ),
        migrations.AddField(
            model_name="weatherobservation",
            name="confianca",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                verbose_name="Confiança",
            ),
        ),
    ]
