# Generated by Django 6.0.6
#
# AgroClima Café — FASE 1
# Indicadores ambientais: UV e ciclo solar.
#
# Migração incremental sobre a estrutura atualmente instalada.
# Nenhum campo existente é removido ou alterado.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "clima",
            "0006_weatherobservation_canonical_contract",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="weatherobservation",
            name="uv_index_max",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Índice UV máximo",
            ),
        ),
        migrations.AddField(
            model_name="weatherobservation",
            name="sunrise",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Nascer do sol",
            ),
        ),
        migrations.AddField(
            model_name="weatherobservation",
            name="sunset",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Pôr do sol",
            ),
        ),
        migrations.AddField(
            model_name="weatherobservation",
            name="daylight_duration_seconds",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Duração da luz do dia (segundos)",
            ),
        ),
    ]


# ==========================================================
# AUDITORIA DA MIGRAÇÃO
# ==========================================================
#
# Dependência:
#   0006_weatherobservation_canonical_contract
#
# Campos adicionados:
#   - uv_index_max
#   - sunrise
#   - sunset
#   - daylight_duration_seconds
#
# Características:
#   - todos os campos aceitam NULL;
#   - não há alteração de dados históricos existentes;
#   - não há remoção ou renomeação de campos;
#   - a migração é incremental;
#   - os tipos correspondem aos campos adicionados em
#     clima/models.py na FASE 1.
#
# Após colocar este arquivo em:
#   clima/migrations/0007_weatherobservation_uv_solar.py
#
# executar no ambiente do projeto:
#
#   python manage.py migrate clima
#
# Somente depois da migração aplicada deve ser executado o
# teste de persistência e coleta dos novos indicadores.
#
# ==========================================================
