# Generated by Django 6.0.6 on 2026-09-07 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clima', '0007_weatherobservation_uv_solar'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='forecast',
            name='clima_forec_station_dc4bdf_idx',
        ),
        migrations.RemoveIndex(
            model_name='forecast',
            name='clima_forec_forecas_d23460_idx',
        ),
        migrations.RemoveConstraint(
            model_name='forecast',
            name='unique_station_forecast',
        ),
        migrations.AddField(
            model_name='historicalweatherdaily',
            name='eto_mm_day',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='ETo diária (mm/dia)'),
        ),
        migrations.DeleteModel(
            name='Forecast',
        ),
    ]
