# Generated by Django 6.0.6 on 2026-10-07 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clima', '0008_remove_forecast_clima_forec_station_dc4bdf_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClimateModelRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('open_meteo_single_runs', 'Open-Meteo Single Runs')], max_length=40)),
                ('model', models.CharField(max_length=32)),
                ('run_datetime', models.DateTimeField()),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lon', models.DecimalField(decimal_places=6, max_digits=9)),
                ('timezone', models.CharField(max_length=64)),
                ('cell_selection', models.CharField(max_length=16)),
                ('requested_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('requested_lon', models.DecimalField(decimal_places=6, max_digits=9)),
                ('elevation', models.DecimalField(decimal_places=6, max_digits=12)),
                ('raw_path', models.TextField()),
                ('raw_sha256', models.CharField(max_length=64)),
                ('content_sha256', models.CharField(max_length=64)),
                ('ingested_at', models.DateTimeField()),
            ],
            options={
                'indexes': [models.Index(fields=['model', 'run_datetime'], name='clima_clima_model_b05d6d_idx'), models.Index(fields=['run_datetime'], name='clima_clima_run_dat_bcef0f_idx')],
                'constraints': [models.UniqueConstraint(fields=('source', 'model', 'run_datetime', 'lat', 'lon', 'cell_selection'), name='climate_model_run_identity_uniq')],
            },
        ),
        migrations.CreateModel(
            name='ClimateForecastRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_datetime', models.DateTimeField()),
                ('variable', models.CharField(max_length=64)),
                ('unit', models.CharField(max_length=16)),
                ('value', models.FloatField(blank=True, null=True)),
                ('value_status', models.CharField(choices=[('NUMERIC', 'Numeric'), ('MISSING', 'Missing')], max_length=8)),
                ('model_run', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='records', to='clima.climatemodelrun')),
            ],
            options={
                'indexes': [models.Index(fields=['forecast_datetime', 'variable'], name='clima_clima_forecas_510273_idx')],
                'constraints': [models.UniqueConstraint(fields=('model_run', 'forecast_datetime', 'variable'), name='climate_forecast_record_identity_uniq'), models.CheckConstraint(condition=models.Q(models.Q(('value__isnull', True), ('value_status', 'MISSING')), models.Q(('value__isnull', False), ('value_status', 'NUMERIC')), _connector='OR'), name='climate_forecast_record_value_status_check')],
            },
        ),
    ]
